create database Medsecura;
use Medsecura;

CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE receptionists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE doctors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE patients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE patients
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN middleName VARCHAR(255),
ADD COLUMN lastName VARCHAR(255) NOT NULL,
ADD COLUMN dob DATE NOT NULL,
ADD COLUMN gender VARCHAR(10) NOT NULL,
ADD COLUMN abhaId VARCHAR(14) NOT NULL,
ADD COLUMN homeAddress TEXT,
ADD COLUMN bloodGroup VARCHAR(5),
ADD COLUMN maritalStatus VARCHAR(20),
ADD COLUMN occupation VARCHAR(255),
ADD COLUMN religion VARCHAR(50),
ADD COLUMN profileImage VARCHAR(255);


ALTER TABLE patients
MODIFY COLUMN password VARCHAR(255) NOT NULL;
